---
title: "Cannonball Data Cleaning and Diagnostics"
author: "Sophie Paolizzi"
date: "8/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
##Load Packages and source scripts
pacman::p_load(tidyverse, readr, janitor, ggplot2,wesanderson, cowplot, flextable)
setwd("~/github_repos/PUBS_Data_Verification/")
#source("Tidy_functions_PUBS.R")

#load data
cannon_data_early_version <- data.table::fread("pubs_pilot_cannon_task_forpilot_6.30.21_raw_21_08_04.csv", fill = TRUE)
cannon_data_late_version <- data.table::fread("pubs_pilot_cannon_task_forpilot_Updated.csv", fill = TRUE)

```

This markdown generates diagnostic checks for the PUBS data.

This chunk tidies the data from the cannonball task. First, I'm doing the old version. I'd like to have this spit out errors too, when possible. 
```{r}

early_subjects <- unique(cannon_data_early_version$subject)

#drop rows that aren't useful - will delete from main script
cannon_data_early_version <- cannon_data_early_version %>% select(!c(build, experimentName, date, time)) %>% group_by(subject) %>% group_by(subject) %>%
  filter(n() > 3) %>% filter(!practiceblock > 0) %>% filter(!subject == "Sophie") %>% mutate(subject = ifelse(subject =="olivia", "300", subject)) ##useful for deleting number of observations less than X

##pipe for organizing data into correct block/trial structure
distinct_early <- cannon_data_early_version %>% 
  group_by(subject, block) %>% ##group by subject and block to prevent weirdness
  mutate_all(function(x) as.character(x)) %>% mutate_all(function(x) as.numeric(x)) %>% ##change needed things to numeric
  mutate(cannonballs_tot = as.numeric(cannonballs_caught + cannonballs_missed)) %>% ##make cannonball_total row to slice based off of
  group_by(subject, block, totalearnings, trialnum) %>% arrange(subject, block, totalearnings, trialnum) %>% ##group and arrange 
  slice(which.max(cannonballs_tot)) ## make the slice


obj_early <- distinct_early %>% group_by(subject, block, totalearnings) %>% summarise(obscount = n(), ) %>% 
  arrange(subject,totalearnings) %>% mutate(block_code = row_number()) %>% group_by(subject) %>% mutate(taskearnings = max(totalearnings)) ##summarize counts and get block numbers

distinct_early <- distinct_early %>% left_join(obj_early, by = c("subject", "block", "totalearnings")) %>% filter(obscount > 2) #filter out totalearnings row
  
##pipe for mutating needed variables
  
  distinct_early <- distinct_early %>% mutate(PE = ang - r) %>% mutate(abs_PE = ifelse(abs(PE)<= 180, abs(PE), abs(abs(PE)-180))) %>% mutate(changepoint = ifelse(StaySwitch == 1 , trialnum, NA)) %>%
    group_by(subject, block, totalearnings) %>% mutate(task_phase = ifelse(block == 1, "oddball", "changepoint")) #create predidction error
  
  
```



This chunk tidies the data from the cannonball task. Now, I'm doing the new version. I'd like to have this spit out errors too, when possible. 
```{r cars}

names(cannon_data_late_version)[22] <- "trial_earnings"
names(cannon_data_late_version)[17] <- "surprise_dup"

late_subjects <- unique(cannon_data_late_version$subject)

#drop rows that aren't useful - will delete from main script
cannon_data_late_version <- cannon_data_late_version %>% group_by(subject) %>% group_by(subject) %>%
  filter(n() > 50) %>% filter(!practiceblock > 0) %>% separate(picture.shield.currentitem, c("Number","Extra"), sep = "-r") %>%
  separate(Number, c("Arc","shield_size"), sep = "c") %>% 
  select(!c(build, experimentName, date, time, Arc, Extra)) %>% mutate(subject = ifelse(subject =="olivia", "300", subject))  ##useful for deleting number of observations less than X

##pipe for organizing data into correct block/trial structure
distinct_late <- cannon_data_late_version %>% 
  group_by(subject, block) %>% ##group by subject and block to prevent weirdness
  mutate_all(function(x) as.character(x)) %>% mutate_all(function(x) as.numeric(x)) %>% ##change needed things to numeric
  mutate(cannonballs_tot = as.numeric(cannonballs_caught + cannonballs_missed)) %>% ##make cannonball_total row to slice based off of
  group_by(subject, block, totalearnings, trialnum) %>% arrange(subject, block, totalearnings, trialnum) %>% ##group and arrange 
  slice(which.max(cannonballs_tot)) ## make the slice


obj_late <- distinct_late %>% group_by(subject, block, totalearnings) %>% summarise(obscount = n(), ) %>% 
  arrange(subject,totalearnings) %>% mutate(block_code = row_number()) %>% group_by(subject) %>% mutate(taskearnings = max(totalearnings)) ##summarize counts and get block numbers

distinct_late <- distinct_late %>% left_join(obj_late, by = c("subject", "block", "totalearnings")) %>% filter(obscount > 2) #filter out totalearnings row
  
##pipe for mutating needed variables
  
  distinct_late <- distinct_late %>% mutate(PE = angrand - placementAngle) %>% mutate(abs_PE = ifelse(abs(PE)<= 180, abs(PE), abs(abs(PE)-180))) %>% mutate(changepoint = ifelse(StaySwitch == 1 , trialnum, NA)) %>%
    group_by(subject, block, totalearnings) %>% mutate(task_phase = ifelse(block == 1, "oddball", "changepoint"))#create predidction error
```
  

```{r}
InBoth <- intersect(colnames(distinct_early), colnames(distinct_late))

distinct_early <- distinct_early %>% mutate(subject = as.character(subject)) %>% mutate(subject = as.numeric(subject), block = as.numeric(as.character(block))) 

distinct_late <- distinct_late %>% mutate(subject = as.numeric(subject), block = as.numeric(block))

distinct <- rbind(distinct_early[,InBoth], distinct_late[,InBoth])

distinct <- distinct %>% filter(!subject == 483419443) %>% mutate( )

rm(distinct_early, distinct_late, cannon_data_early_version, cannon_data_late_version,InBoth, early_subjects, late_subjects)
```
  
  
  
  
  
```{r}
subjects <- as.character(unique(distinct$subject)); plot_subjects <- list()
for (i in subjects) {
  d <- distinct %>% dplyr::filter(subject == i && task_phase == "oddball")
  oddball <- ggplot(d, aes(x=trialnum, y=abs_PE)) + 
     geom_point() +
     geom_vline(aes(xintercept = changepoint, color = "Oddball")) + 
     xlab("Trial Number") + ylab("Response Type") + ggtitle(i) +
     facet_wrap(~block_code)

 change_point <- ggplot(distinct %>% dplyr::filter(subject == i && task_phase == "changepoint"), aes(x=trialnum, y=abs_PE)) + 
     geom_point() +
     geom_vline(aes(xintercept = changepoint, color = "Changepoint")) + 
     xlab("Trial Number") + ylab("Response Type") + ggtitle(i) +
     facet_wrap(~block_code)
  plot_subjects[[i]] <- list(oddball, change_point) 
 
}



subjects <- as.character(unique(distinct$subject)); plot_subjects <- list()
for (i in subjects) {
  d <- distinct %>% dplyr::filter(subject == i && task_phase == "oddball")
  oddball <- ggplot(d, aes(x=trialnum, y=abs_PE)) + 
     geom_point() +
     geom_vline(aes(xintercept = changepoint, color = "Oddball")) + 
     xlab("Trial Number") + ylab("Response Type") + ggtitle(i) +
     facet_wrap(~block_code)

 change_point <- ggplot(distinct %>% dplyr::filter(subject == i && task_phase == "changepoint"), aes(x=trialnum, y=abs_PE)) + 
     geom_point() +
     geom_vline(aes(xintercept = changepoint, color = "Changepoint")) + 
     xlab("Trial Number") + ylab("Response Type") + ggtitle(i) +
     facet_wrap(~block_code)
  plot_subjects[[i]] <- list(oddball, change_point) 
 
}



#colormatrix <- ifelse(obj$above_threshold == "Below", wes_palette("Cavalcanti1")[c(4)], "white") ##potentially save these as bad_blocks vector
#tab <- obj %>% flextable() %>% bg(j = 1:8, bg=colormatrix)

#tab
plot_subjects
```
 