---
title: "PUBS_Assignment_Week8"
author: "Sophie Paolizzi"
date: "10/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
options(knitr.duplicate.label = "allow")
##Load Packages and source scripts
pacman::p_load(tidyverse, readr, janitor, ggplot2,wesanderson, cowplot, flextable, plotly, qualtRics)
setwd("~/github_repos/PUBS_Data_Verification/") ##Set this to be whereever you're storing the data

surveys <- all_surveys()
qualtrics <- fetch_survey(surveyID = surveys$id[18],
                         convert = FALSE, label = FALSE, verbose = FALSE, force_request = TRUE)
# 
# qualtrics <- read_survey("Qualtrics_Data/PUBS_Batch1_QR.csv")
```

```{r cars}
qualtrics <- qualtrics %>% dplyr::filter(!StartDate < "2021-10-01") %>% dplyr::filter(Progress == "100") %>% rename(age = Q242_1) %>% mutate(age == as.numeric(age)) %>% filter(age <= 45) %>% filter(!is.na(	
workerId))
# qualtrics <- qualtrics %>% select(c(1:230, 779)) #rough way of doing this but it works
options <- "by_questionnaire"
```

```{r}
columns <- colnames(qualtrics)
global_vars <- (c("RandomID", "Eth", "gen", "age")) #copy names of all demographic variables in here.
```

```{r pressure, echo=FALSE}
if (options == "by_questionnaire"){
  PID <- qualtrics %>% dplyr::select(RandomID, contains("PID")); PID <- as.data.frame(lapply(PID, as.numeric))
  PSWQ <- qualtrics %>% dplyr::select(RandomID, SC2, contains("PSWQ"));  PSWQ <- as.data.frame(lapply(PSWQ, as.numeric))
  PAI <- qualtrics %>% dplyr::select(RandomID, SC1, contains("PAI"));  PAI <- as.data.frame(lapply(PAI, as.numeric))
  BFAS <- qualtrics %>% dplyr::select(RandomID, contains("BFAS"));  BFAS <- as.data.frame(lapply(BFAS, as.numeric))
  STAI <- qualtrics %>% dplyr::select(RandomID, contains("STAI"));  STAI <- as.data.frame(lapply(STAI, as.numeric))
  global_variables <- qualtrics[, (names(qualtrics) %in% global_vars)]
  measures_list <- list(PID, PSWQ, PAI, BFAS, STAI, global_variables)
  expected_vals <- c(109, 16, 24, 20, 40, 3) #PLEASE UPDATE THIS VECTOR WITH YOUR EXPECTED COUNT
  names(measures_list) <- c("PID", "PSWQ", "PAI", "BFAS", "STAI", "GLOBAL")
  measures_list
}
```


#Quick Check to make sure we have the number of columns we expect
```{r}
  summary_df <- as.data.frame(summary(measures_list))
  summary_df <- summary_df[1:6, c(1,3)]
  summary_df$Expected_Vals <- expected_vals 
  summary_df <- rename(summary_df, "Questionnaire" = "Var1")
  summary_df %>%
    mutate(Match = if(Freq == Expected_Vals){
      TRUE
    }else{
      FALSE
    }
)
  
```




```{r}
# PAI <- PAI %>%
#   mutate(across(
#         starts_with("PAI") & ends_with(c("7","12","14","19","20","24")),
#         ~recode(., `1` ="3",
#                 `2` = "2" ,
#                 `3` = "1",
#                 `4` = "0")
#         )) %>%
#   mutate(across(
#         starts_with("PAI") & !ends_with(c("7","12","14","19","20","24")),
#         ~recode(., `1` = "0",
#                 `2` = "1" ,
#                 `3`= "2",
#                 `4` = "3")))
# 
# 
# PSWQ <- PSWQ %>%
#   mutate(across(
#         starts_with("PSWQ") & !ends_with(c("2", "4", "5", "6", "7", "9", "12", "13", "14", "15", "16")),
#         ~recode(., `1` = "5",
#                 `2` = "4" ,
#                 `3` = "3",
#                 `4` = "2",
#                 `5` = "1")
#         )) %>%
#   mutate(across(
#         starts_with("PAI") & ends_with(c("2", "4", "5", "6", "7", "9", "12", "13", "14", "15", "16")),
#          ~recode(., `1` = "1",
#                 `2` = "2" ,
#                 `3` = "3",
#                 `4` = "4",
#                 `5` = "5")))
# 
# # PAI <- PAI %>%
#   mutate(across(
#         starts_with("PAI") & ends_with(c("7","12","14","19","20","24")),
#         ~recode(., "False, not at all true" = "3",
#                                 "Slightly True" = "2" ,
#                                 "Mainly True" = "1",
#                                 "Very True" = "0",
#                 .default = .)
#         )) %>%
#   mutate(across(
#         starts_with("PAI") & !ends_with(c("7","12","14","19","20","24")),
#         ~recode(., "False, not at all true" = "0",
#                                 "Slightly True" = "1" ,
#                                 "Mainly True" = "2",
#                                 "Very True" = "3",
#                 .default = .)
#         ))
# PAI <- as.data.frame(lapply(PAI, as.numeric))
# PSWQ <- as.data.frame(lapply(PSWQ, as.numeric))
```


#How many PTs are meeting cutoffs, aslo how to seperate into subscales
```{r}

#PTs over PAI Cutoff
#seperate into subscales
PAI$PAI_Score <- NULL
for (i in 1:nrow(PAI)){
  PAI$PAI_Tot[i] <- sum(PAI[i, 2:25], na.rm = TRUE)
}


#need to sort out a few questions, this should be about 100 qs
#need to sort into subscales
PID$PID_Tot <- NULL
for (i in 1:nrow(PAI)){
  PID$PID_Tot[i] <- sum(PID[i, 2:110], na.rm = TRUE)
}


#seperate into subscales
STAI$STAI_Tot <- NULL
for (i in 1:nrow(PAI)){
  STAI$STAI_Tot[i] <- sum(STAI[i, 2:41], na.rm = TRUE)
}


#seperate BFAS into subscales
BFAS$BFAS_Tot <- NULL
for (i in 1:nrow(PAI)){
  BFAS$BFAS_Tot[i] <- sum(BFAS[i, 2:21], na.rm = TRUE)
}


#PTs over PAI Cutoff
PSWQ$PSWQ_Tot <- NULL
for (i in 1:nrow(PAI)){
  PSWQ$PSWQ_Tot[i] <- sum(PSWQ[i, 2:17], na.rm = TRUE)
}



hist(PAI$PAI_); summary(PAI$PAI_Tot)
hist(PSWQ$PSWQ_Tot); summary(PSWQ$PSWQ_Tot)

corr <- left_join(PAI, PSWQ, by = "RandomID")


Elev_Samp <- corr %>% filter(PSWQ_Tot > 64 | PAI_Tot > 39) %>% select(RandomID, PAI_Tot, PSWQ_Tot)


PSWQ_over_cutoff <- corr %>% filter(PSWQ_Tot > 64) %>% filter(PAI_Tot < 39)
PAI_over_cutoff <- corr %>% filter(PAI_Tot > 39) %>% filter(PSWQ_Tot < 64) 

plot(corr$PAI_Tot, corr$PSWQ_Tot)


```



#
```{r}
  measures_df <- cbind(global_variables, PID, PSWQ, PAI, BFAS, STAI)
  measures_df <- measures_df[!duplicated(as.list(measures_df))]
  save(measures_df, file = "~/github_repos/PUBS_Data_Verification/Qualtrics_Data/PUBS_Batch1_QR_Proc.R" )
```


